version: "3.9"

services:
#  web:
#    build: .
#    depends_on:
#      - db
#    environment:
#      DUMMY: 'dummy_text_default'

  db:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'starwars'
      MYSQL_USER: 'starwars'
      MYSQL_PASSWORD: 'starwars'
      MYSQL_ROOT_PASSWORD: 'starwars'
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - "3001:8080"
    depends_on:
      - db

volumes:
  data: